# Generated by Django 4.2.6 on 2023-11-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lenguajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lenguaje', models.CharField(default='', max_length=60, verbose_name='Nombre:')),
                ('categoria', models.CharField(choices=[('BackEnd', 'BackEnd'), ('FrontEnd', 'FrontEnd'), ('FullStack', 'FullStack')], default='none', max_length=100, verbose_name='Categoria:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El :')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El :')),
            ],
            options={
                'verbose_name': 'Lenguajes',
                'verbose_name_plural': 'Lenguajes',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(default='', max_length=60, verbose_name='Nombre:')),
                ('image_proyecto', models.ImageField(blank=True, null=True, upload_to='proyects_images/')),
                ('descripcion_proyecto', models.TextField(default='', verbose_name='Descripcion')),
                ('url_proyecto', models.CharField(default='', max_length=100, verbose_name='URL:')),
                ('url_github', models.CharField(default='', max_length=100, verbose_name='Url Github:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El :')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El :')),
                ('tags_proyecto', models.ManyToManyField(default='', related_name='opcion1', to='portafolio.lenguajes', verbose_name='Tags:')),
            ],
            options={
                'verbose_name': 'Proyectos',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
