# Generated by Django 4.2.6 on 2023-11-09 22:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_noticia', models.CharField(default='', max_length=60, verbose_name='Nombre:')),
                ('subnombre_noticia', models.CharField(default='', max_length=60, verbose_name='Nombre:')),
                ('descripcion_proyecto', ckeditor.fields.RichTextField(default='', verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El :')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El :')),
            ],
            options={
                'verbose_name': 'Noticias',
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.AlterField(
            model_name='lenguajes',
            name='categoria',
            field=models.CharField(choices=[('FrontEnd', 'FrontEnd'), ('BackEnd', 'BackEnd'), ('FullStack', 'FullStack')], default='none', max_length=100, verbose_name='Categoria:'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='url_github',
            field=models.CharField(default='', max_length=100, verbose_name='Github:'),
        ),
    ]
