# Generated by Django 4.2.6 on 2023-11-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_remove_noticias_descripcion_proyecto_noticias_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='image_proyecto',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='lenguajes',
            name='categoria',
            field=models.CharField(choices=[('BackEnd', 'BackEnd'), ('FullStack', 'FullStack'), ('FrontEnd', 'FrontEnd')], default='none', max_length=100, verbose_name='Categoria:'),
        ),
    ]
