# Generated by Django 4.2.6 on 2023-11-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_noticias_image_proyecto_alter_lenguajes_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticias',
            old_name='image_proyecto',
            new_name='image_noticia',
        ),
        migrations.AlterField(
            model_name='lenguajes',
            name='categoria',
            field=models.CharField(choices=[('FullStack', 'FullStack'), ('FrontEnd', 'FrontEnd'), ('BackEnd', 'BackEnd')], default='none', max_length=100, verbose_name='Categoria:'),
        ),
    ]
