# Generated by Django 4.2.6 on 2023-11-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0005_rename_image_proyecto_noticias_image_noticia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='slug_noticia',
            field=models.CharField(default='', max_length=60, verbose_name='Url Amigable:'),
        ),
        migrations.AlterField(
            model_name='lenguajes',
            name='categoria',
            field=models.CharField(choices=[('FrontEnd', 'FrontEnd'), ('FullStack', 'FullStack'), ('BackEnd', 'BackEnd')], default='none', max_length=100, verbose_name='Categoria:'),
        ),
    ]
