# Generated by Django 4.2.6 on 2023-11-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0007_noticias_autor_noticia_alter_lenguajes_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_suscripcion', models.CharField(default='', max_length=60, verbose_name='Correo:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El :')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El :')),
            ],
            options={
                'verbose_name': 'Suscripcion',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.AlterModelOptions(
            name='lenguajes',
            options={'verbose_name': 'Lenguaje', 'verbose_name_plural': 'Lenguajes'},
        ),
        migrations.AlterModelOptions(
            name='noticias',
            options={'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelOptions(
            name='proyectos',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterField(
            model_name='lenguajes',
            name='categoria',
            field=models.CharField(choices=[('FrontEnd', 'FrontEnd'), ('BackEnd', 'BackEnd'), ('FullStack', 'FullStack')], default='none', max_length=100, verbose_name='Categoria:'),
        ),
    ]
