# Generated by Django 4.2.6 on 2023-11-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0008_suscripciones_alter_lenguajes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenguajes',
            name='categoria',
            field=models.CharField(choices=[('BackEnd', 'BackEnd'), ('FullStack', 'FullStack'), ('FrontEnd', 'FrontEnd')], default='none', max_length=100, verbose_name='Categoria:'),
        ),
    ]
